#pragma once
#include QMK_KEYBOARD_H
#include "layers.h"

// LAYER KEYCODES
#define _KC_T LT(_FN,KC_T)
#define _KC_S LT(_NUM, KC_S)
#define _KC_K LT(_CODE, KC_K)
#define _OSL_SYM OSL(_SYM)

// FANCY QUOTES KEYCODES
#define _LDFQUO LALT(KC_LBRACKET)
#define _RDFQUO LALT(LSFT(KC_LBRACKET))
#define _LFQUO LALT(KC_RBRACKET)
#define _RFQUO LALT(LSFT(KC_RBRACKET))

// ONE-SHOT MODIFIERS
#define _OSM_LCMD OSM(MOD_LGUI)
#define _OSM_RCMD OSM(MOD_RGUI)
#define _OSM_LSHIFT OSM(MOD_LSFT)
#define _OSM_RSHIFT OSM(MOD_RSFT)
#define _OSM_OPT OSM(MOD_LALT)
#define _OSM_CTR OSM(MOD_LCTL)
#define _OSM_CMDALT OSM(MOD_LGUI | MOD_LALT)

// PROGRAMMING SHORTCUTS
#define _MEH_LBRKT MEH(KC_LBRACKET)
#define _MEH_RBRKT MEH(KC_RBRACKET)

// MOUSE KEYCODE
#define _SHFT_WHDN LSFT(KC_MS_WH_DOWN)
#define _SHFT_WHUP LSFT(KC_MS_WH_UP)

// GLOBAL HOTKEYS
#define _ZOOM_IN HYPR(KC_EQUAL)
#define _ZOOM_OUT HYPR(KC_MINUS)
#define _FORWARD MEH(KC_UP)
#define _BACK MEH(KC_DOWN)

// MOD TAPS
// #define _SPACE MT(MOD_LSFT | MOD_LALT, KC_SPACE)
#define _SHFT_ENTER MT(MOD_RSFT, KC_ENTER)
#define _KC_A MT(MOD_LALT, KC_A)
#define _KC_R MT(MOD_LSFT, KC_R)

// OTHER KEYCODES
#define _UNDO LGUI(KC_Z)
#define _REDO LGUI(LSFT(KC_Z))
#define _LAYER_LEDS TOGGLE_LAYER_COLOR
#define _SCREEN_DN KC_BRIGHTNESS_DOWN
#define _SCREEN_UP KC_BRIGHTNESS_UP
#define _PREV KC_MEDIA_PREV_TRACK
#define _NEXT KC_MEDIA_NEXT_TRACK
#define _VOL_UP KC_AUDIO_VOL_UP
#define _VOL_DOWN KC_AUDIO_VOL_DOWN

// custom tap dances
#define _KC_UP_DIR  LT(0, KC_0)
#define _SPACE LT(0, KC_SPACE)
#define _DOT LT(0, KC_DOT)
#define _COMMA LT(0, KC_COMMA)


// CUSTOM KEYCODES
enum custom_keycodes {
	_KC_COMMENT = EZ_SAFE_RANGE,
	_KC_CUR_DIR,
	_KC_NIX_HOME,
	_KC_AND,
	_KC_OR,
};

