#undef COMBO_TERM
#undef COMBO_HOLD_TERM

#define COMBO_TERM 26
#define COMBO_HOLD_TERM 200

#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_PROCESS_KEY_RELEASE
#define EXTRA_SHORT_COMBOS
#define COMBO_MUST_HOLD_PER_COMBO
#define COMBO_COMBO_TERM_PER_COMBO
#define COMBO_STRICT_TIMER
