#pragma once
#include QMK_KEYBOARD_H
#include "../definitions/layers.h"
#include "../definitions/keycodes.h"
#include "lighting.h"
#include "leader.h"


/**
 * TAP DANCE CODES
 */
enum tap_dance_codes {
	DANCE_SPOTLIGHT,
	DANCE_SPACE_LAST_APP,
	DANCE_TAB_MGMT,
	DANCE_PGUP_HOME,
	DANCE_PGDN_END,
	DANCE_ZOOM_OUT,
	DANCE_SEMICOLON,
	DANCE_SLASH_COLON,
	DANCE_QUOTE,
	DANCE_DOT,
	DANCE_COMMA,
	DANCE_VOL_DN,
	DANCE_PAREN,
	DANCE_BRACKET,
	DANCE_CBRACKET,
	DANCE_PLAY,
	DANCE_DQUOTE,
	DANCE_DASH,
	DANCE_L_QUOTE,
	DANCE_GTEQ,
	DANCE_LTEQ,
	DANCE_DESKTOP,
	DANCE_UP_DIR,
	DANCE_APP_WINDOWS,
	DANCE_APP_TABS,

	// leave this for initializing dance_state in tapdance.h
	NUM_DANCE_CODES,
};


// TAP DANCE KEY CODES
#define _ZOOM_OUT TD(DANCE_ZOOM_OUT)
#define _VOL_DOWN TD(DANCE_VOL_DN)
#define _PLAY TD(DANCE_PLAY)
#define _QUOTE TD(DANCE_QUOTE)
#define _DQUOTE TD(DANCE_DQUOTE)
#define _DOT TD(DANCE_DOT)
#define _COMMA TD(DANCE_COMMA)
#define _TAB_MGMT TD(DANCE_TAB_MGMT)
#define _PGUP_HOME TD(DANCE_PGUP_HOME)
#define _PGDN_END TD(DANCE_PGDN_END)
#define _DESKTOP TD(DANCE_DESKTOP)
#define _SPOTLIGHT TD(DANCE_SPOTLIGHT)
#define _SPACE TD(DANCE_SPACE_LAST_APP)
#define _SLASH_COLON TD(DANCE_SLASH_COLON)
#define _SEMICOLON TD(DANCE_SEMICOLON)
#define _LCBR TD(DANCE_CBRACKET)
#define _LBRACKET TD(DANCE_BRACKET)
#define _LPRN TD(DANCE_PAREN)
#define _GTEQ TD(DANCE_GTEQ)
#define _LTEQ TD(DANCE_LTEQ)
#define _KC_UP_DIR TD(DANCE_UP_DIR)
#define _HYPHEN TD(DANCE_DASH)
#define _APP_WINDOWS TD(DANCE_APP_WINDOWS)
#define _APP_TABS TD(DANCE_APP_TABS)



// STUFF FOR TAP DANCE
typedef struct {
	bool is_press_action;
	uint8_t step;
} tap;

enum {
	SINGLE_TAP = 1,
	SINGLE_HOLD,
	DOUBLE_TAP,
	DOUBLE_HOLD,
	DOUBLE_SINGLE_TAP,
	MORE_TAPS
};

uint8_t dance_step(qk_tap_dance_state_t *state);
